# Generated by Django 4.2.1 on 2023-05-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_servis_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servis',
            name='test',
        ),
    ]
